export enum ErrorCode {

    // Users related errors.
    USER_ALREADY_EXISTS = 1001,
    USER_NOT_FOUND = 1002,
    FIRST_ADMIN_ACCOUNT_ALREADY_EXISTS = 1003,
    USER_CANNOT_DEACTIVATE_SELF = 1004,
    USER_ALREADY_DEACTIVATED = 1005,
    USER_ALREADY_ACTIVATED = 1006,
    OLD_PASSWORD_INCORRECT = 1007,

    CREATE_USER_SERVICE = 1101,
    GET_USER_BY_ID_SERVICE = 1102,
    GET_USER_BY_USERNAME_SERVICE = 1103,
    GET_LIST_OF_USERS_SERVICE = 1104,
    DEACTIVATE_USER_SERVICE = 1105,
    ACTIVATE_USER_SERVICE = 1106,
    EDIT_USER_SERVICE = 1107,
    FORGOT_PASSWORD_SERVICE = 1108,
    USER_CHANGE_PASSWORD_SERVICE = 1109,
    SEARCH_USERS_SERVICE = 1110,

    // Auth related errors.
    USERNAME_OR_PASSWORD_INCORRECT = 2001,
    INVALID_JWT_PAYLOAD = 2002,
    INVALID_JWT_TOKEN = 2003,
    NO_ROLES_FOUND_FOR_USER = 2004,
    REQUIRED_ROLES_NOT_FOUND = 2005,
    INVALID_REFRESH_TOKEN = 2006,
    RATE_LIMIT_EXCEEDED = 2007,
    TOO_MANY_REFRESH_TOKENS = 2008,

    LOGIN_SERVICE = 2101,
    NEW_ACCESS_TOKEN_SERVICE = 2102,
    LOGOUT_SERVICE = 2103,
    VALIDATE_REFRESH_TOKEN_SERVICE = 2104,
    VALIDATE_REFRESH_TOKEN_BY_ID_SERVICE = 2105,
    REVOKE_ALL_REFRESH_TOKENS_SERVICE = 2106,


    // Products related errors.
    PRODUCT_UNIT_NOT_FOUND = 3001,
    PRODUCT_UNIT_NAME_ALREADY_EXISTS = 3002,
    PRODUCT_UNIT_ALREADY_ACTIVATED = 3003,
    PRODUCT_UNIT_ALREADY_DEACTIVATED = 3004,
    PRODUCT_UNIT_NOT_ACTIVE = 3005,
    PRODUCT_SKU_ALREADY_EXISTS = 3006,
    PRODUCT_NOT_FOUND = 3007,
    PRODUCT_NOT_ACTIVE = 3008,
    PRODUCT_ALREADY_ACTIVATED = 3009,
    PRODUCT_ALREADY_DEACTIVATED = 3010,
    PRODUCT_STOCK_CANNOT_BE_NEGATIVE = 3011,
    PRODUCT_STOCK_HISTORY_NOT_FOUND = 3012,
    TOO_MANY_PRODUCT_NAMES = 3013,

    CREATE_PRODUCT_UNIT_SERVICE = 3101,
    EDIT_PRODUCT_UNIT_SERVICE = 3102,
    GET_PRODUCT_UNIT_BY_ID_SERVICE = 3103,
    GET_LIST_OF_PRODUCT_UNITS_SERVICE = 3104,
    DEACTIVATE_PRODUCT_UNIT_SERVICE = 3105,
    ACTIVATE_PRODUCT_UNIT_SERVICE = 3106,
    CREATE_PRODUCT_SERVICE = 3107,
    EDIT_PRODUCT_SERVICE = 3108,
    GET_PRODUCT_SERVICE = 3109,
    GET_PRODUCTS_SERVICE = 3110,
    GET_PRODUCT_CASHIER_SERVICE = 3111,
    ACTIVATE_PRODUCT_SERVICE = 3112,
    DEACTIVATE_PRODUCT_SERVICE = 3113,
    GET_PRODUCT_UNIT_HISTORY_LIST_SERVICE = 3114,
    GET_PRODUCT_UNIT_HISTORY_BY_VERSION_SERVICE = 3115,
    GET_PRODUCT_HISTORY_LIST_SERVICE = 3116,
    GET_PRODUCT_HISTORY_BY_VERSION_SERVICE = 3117,
    UPDATE_INVENTORY_STOCK_BULK_SERVICE = 3118,
    GET_PRODUCT_STOCK_HISTORY_LIST_SERVICE = 3119,

    // General invoice errors.
    INVOICE_NOT_FOUND = 4001,
    INVOICE_NOT_DRAFT = 4002,
    INVOICE_NOT_CONFIRMED = 4003,
    INVOICE_NO_PERMISSION_DRAFT = 4004,

    // import-invoices errors.
    TOO_MANY_IMPORT_INVOICE_PRODUCTS = 4005,

    // return-import-invoices errors.
    TOO_MANY_RETURN_IMPORT_INVOICE_PRODUCTS = 4006,

    // selling-invoices errors.
    TOO_MANY_SELLING_INVOICE_PRODUCTS = 4007,

    // return-selling-invoices errors.
    TOO_MANY_RETURN_SELLING_INVOICE_PRODUCTS = 4008,

    // stock-adjustment-invoices errors.
    TOO_MANY_STOCK_ADJUSTMENT_INVOICE_PRODUCTS = 4009,

    // import-invoices services.
    CREATE_DRAFT_IMPORT_INVOICE_SERVICE = 4101,
    EDIT_DRAFT_IMPORT_INVOICE_SERVICE = 4102,
    DELETE_DRAFT_IMPORT_INVOICE_SERVICE = 4103,
    CONFIRM_IMPORT_INVOICE_SERVICE = 4104,
    GET_IMPORT_INVOICE_BY_ID_SERVICE = 4105,
    GET_LIST_OF_IMPORT_INVOICES_SERVICE = 4106,

    // return-import-invoices services.
    CREATE_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 4201,
    EDIT_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 4202,
    DELETE_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 4203,
    CONFIRM_RETURN_IMPORT_INVOICE_SERVICE = 4204,
    GET_RETURN_IMPORT_INVOICE_BY_ID_SERVICE = 4205,
    GET_LIST_OF_RETURN_IMPORT_INVOICES_SERVICE = 4206,

    // selling-invoices services.
    CREATE_SELLING_INVOICE_SERVICE = 4301,
    GET_SELLING_INVOICE_BY_ID_SERVICE = 4302,
    GET_LIST_OF_SELLING_INVOICES_SERVICE = 4303,

    // return-selling-invoices services.
    CREATE_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 4401,
    EDIT_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 4402,
    DELETE_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 4403,
    CONFIRM_RETURN_SELLING_INVOICE_SERVICE = 4404,
    GET_RETURN_SELLING_INVOICE_BY_ID_SERVICE = 4405,
    GET_LIST_OF_RETURN_SELLING_INVOICES_SERVICE = 4406,

    // stock-adjustment-invoices services.
    CREATE_DRAFT_STOCK_ADJUSTMENT_INVOICE_SERVICE = 4501,
    EDIT_DRAFT_STOCK_ADJUSTMENT_INVOICE_SERVICE = 4502,
    DELETE_DRAFT_STOCK_ADJUSTMENT_INVOICE_SERVICE = 4503,
    CONFIRM_STOCK_ADJUSTMENT_INVOICE_SERVICE = 4504,
    GET_STOCK_ADJUSTMENT_INVOICE_BY_ID_SERVICE = 4505,
    GET_LIST_OF_STOCK_ADJUSTMENT_INVOICES_SERVICE = 4506,

    // Logs AND Dashboard related errors.
    LOG_NOT_FOUND = 5001,
    DATE_CAN_NOT_BE_IN_FUTURE = 5002,
    END_DATE_MUST_BE_PROVIDED = 5003,
    DATE_RANGE_TOO_LARGE = 5004,

    GET_LIST_PRODUCT_RANKING_SERVICE = 5101,

    // DTO validation error.
    DTO_VALIDATION_ERROR = 9001,

    // HTTP exception error.
    HTTP_EXCEPTION = 9901,

    // Unknown error.
    UNKNOWN_ERROR = 9999,
}