export enum ErrorCode {

    // Users related errors.
    USER_ALREADY_EXISTS = 1001,
    USER_NOT_FOUND = 1002,
    FIRST_ADMIN_ACCOUNT_ALREADY_EXISTS = 1003,
    USER_CANNOT_DEACTIVATE_SELF = 1004,
    USER_ALREADY_DEACTIVATED = 1005,
    USER_ALREADY_ACTIVATED = 1006,
    OLD_PASSWORD_INCORRECT = 1007,

    CREATE_USER_SERVICE = 1101,
    GET_USER_BY_ID_SERVICE = 1102,
    GET_USER_BY_USERNAME_SERVICE = 1103,
    GET_LIST_OF_USERS_SERVICE = 1104,
    DEACTIVATE_USER_SERVICE = 1105,
    ACTIVATE_USER_SERVICE = 1106,
    EDIT_USER_SERVICE = 1107,
    FORGOT_PASSWORD_SERVICE = 1108,
    USER_CHANGE_PASSWORD_SERVICE = 1109,
    SEARCH_USERS_SERVICE = 1110,

    // Auth related errors.
    USERNAME_OR_PASSWORD_INCORRECT = 2001,
    INVALID_JWT_PAYLOAD = 2002,
    INVALID_JWT_TOKEN = 2003,
    NO_ROLES_FOUND_FOR_USER = 2004,
    REQUIRED_ROLES_NOT_FOUND = 2005,
    INVALID_REFRESH_TOKEN = 2006,
    RATE_LIMIT_EXCEEDED = 2007,
    TOO_MANY_REFRESH_TOKENS = 2008,

    LOGIN_SERVICE = 2101,
    NEW_ACCESS_TOKEN_SERVICE = 2102,
    LOGOUT_SERVICE = 2103,
    VALIDATE_REFRESH_TOKEN_SERVICE = 2104,
    VALIDATE_REFRESH_TOKEN_BY_ID_SERVICE = 2105,
    REVOKE_ALL_REFRESH_TOKENS_SERVICE = 2106,

    // Logs related errors.
    LOG_DIFFERENCES_NOT_FOUND = 3001,
    LOG_NOT_FOUND = 3002,
    LOG_NOT_REVERTABLE = 3003,
    CANNOT_REVERT_NEWEST_LOG = 3004,

    CREATE_LOG_SERVICE = 3101,
    CREATE_LOG_DIFFERENCE_SERVICE = 3102,
    GET_LIST_OF_LOGS_SERVICE = 3103,
    GET_ALL_LOG_DIFFERENCES_BY_LOG_ID_SERVICE = 3104,
    GET_ALL_LOGS_USER_ENTITY_ID_SERVICE = 3105,
    REVERT_USER_DATABASE_SERVICE = 3106,

    // Products related errors.
    PRODUCT_UNIT_NOT_FOUND = 4001,
    PRODUCT_UNIT_NAME_ALREADY_EXISTS = 4002,
    PRODUCT_UNIT_ALREADY_ACTIVATED = 4003,
    PRODUCT_UNIT_ALREADY_DEACTIVATED = 4004,
    PRODUCT_UNIT_NOT_ACTIVE = 4005,
    PRODUCT_SKU_ALREADY_EXISTS = 4006,
    PRODUCT_NOT_FOUND = 4007,
    PRODUCT_NOT_ACTIVE = 4008,
    PRODUCT_ALREADY_ACTIVATED = 4009,
    PRODUCT_ALREADY_DEACTIVATED = 4010,
    PRODUCT_STOCK_CANNOT_BE_NEGATIVE = 4011,
    PRODUCT_STOCK_HISTORY_NOT_FOUND = 4012,

    CREATE_PRODUCT_UNIT_SERVICE = 4101,
    EDIT_PRODUCT_UNIT_SERVICE = 4102,
    GET_PRODUCT_UNIT_BY_ID_SERVICE = 4103,
    GET_LIST_OF_PRODUCT_UNITS_SERVICE = 4104,
    DEACTIVATE_PRODUCT_UNIT_SERVICE = 4105,
    ACTIVATE_PRODUCT_UNIT_SERVICE = 4106,
    CREATE_PRODUCT_SERVICE = 4107,
    EDIT_PRODUCT_SERVICE = 4108,
    GET_PRODUCT_SERVICE = 4109,
    GET_PRODUCTS_SERVICE = 4110,
    GET_PRODUCT_CASHIER_SERVICE = 4111,
    ACTIVATE_PRODUCT_SERVICE = 4112,
    DEACTIVATE_PRODUCT_SERVICE = 4113,
    UPDATE_INVENTORY_STOCK_SERVICE = 4114,
    GET_PRODUCT_UNIT_HISTORY_LIST_SERVICE = 4115,
    GET_PRODUCT_UNIT_HISTORY_BY_VERSION_SERVICE = 4116,
    GET_PRODUCT_HISTORY_LIST_SERVICE = 4117,
    GET_PRODUCT_HISTORY_BY_VERSION_SERVICE = 4118,
    CREATE_PRODUCT_STOCK_HISTORY_SERVICE = 4119,
    UPDATE_INVENTORY_STOCK_BULK_SERVICE = 4120,
    GET_PRODUCT_STOCK_HISTORY_LIST_SERVICE = 4121,
    GET_PRODUCT_STOCK_HISTORY_BY_ID_SERVICE = 4122,

    // Invoice related errors.
    TOO_MANY_IMPORT_INVOICE_PRODUCTS = 5001,
    INVOICE_NOT_FOUND = 5002,
    INVOICE_NOT_DRAFT = 5003,
    INVOICE_NOT_CONFIRMED = 5004,
    INVOICE_NO_PERMISSION_DRAFT = 5005,

    TOO_MANY_STOCK_ADJUSTMENT_PRODUCTS = 5006,
    STOCK_ADJUSTMENT_NOT_FOUND = 5007,
    STOCK_ADJUSTMENT_NOT_DRAFT = 5008,
    STOCK_ADJUSTMENT_NOT_CONFIRMED = 5009,
    STOCK_ADJUSTMENT_NO_PERMISSION_DRAFT = 5010,

    CREATE_DRAFT_IMPORT_INVOICE_SERVICE = 5101,
    EDIT_DRAFT_IMPORT_INVOICE_SERVICE = 5102,
    DELETE_DRAFT_IMPORT_INVOICE_SERVICE = 5103,
    CONFIRM_IMPORT_INVOICE_SERVICE = 5104,
    GET_IMPORT_INVOICE_BY_ID_SERVICE = 5105,
    GET_LIST_OF_IMPORT_INVOICES_SERVICE = 5106,
    CANCEL_IMPORT_INVOICE_SERVICE = 5107,

    CREATE_DRAFT_STOCK_ADJUSTMENT_SERVICE = 5108,
    EDIT_DRAFT_STOCK_ADJUSTMENT_SERVICE = 5109,
    DELETE_DRAFT_STOCK_ADJUSTMENT_SERVICE = 5110,
    CONFIRM_STOCK_ADJUSTMENT_SERVICE = 5111,
    CANCEL_STOCK_ADJUSTMENT_SERVICE = 5112,
    GET_STOCK_ADJUSTMENT_BY_ID_SERVICE = 5113,
    GET_LIST_OF_STOCK_ADJUSTMENTS_SERVICE = 5114,

    CREATE_SELLING_INVOICE_SERVICE = 5115,
    CANCEL_SELLING_INVOICE_SERVICE = 5116,
    GET_SELLING_INVOICE_BY_ID_SERVICE = 5117,
    GET_LIST_OF_SELLING_INVOICES_SERVICE = 5118,

    // DTO validation error.
    DTO_VALIDATION_ERROR = 9001,

    // HTTP exception error.
    HTTP_EXCEPTION = 9901,

    // Unknown error.
    UNKNOWN_ERROR = 9999,
}