export enum LogCode {
    CREATE_NEW_USER = 'CREATE_NEW_USER',
    EDIT_USER_INFORMATION = 'EDIT_USER_INFORMATION',
    DEACTIVATE_USER = 'DEACTIVATE_USER',
    ACTIVATE_USER = 'ACTIVATE_USER',
    ADMIN_RESET_PASSWORD = 'ADMIN_RESET_PASSWORD',

    CREATE_NEW_PRODUCT_UNIT = 'CREATE_NEW_PRODUCT_UNIT',
    EDIT_PRODUCT_UNIT = 'EDIT_PRODUCT_UNIT',
    DEACTIVATE_PRODUCT_UNIT = 'DEACTIVATE_PRODUCT_UNIT',
    ACTIVATE_PRODUCT_UNIT = 'ACTIVATE_PRODUCT_UNIT',

    CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT',
    EDIT_PRODUCT = 'EDIT_PRODUCT',
    DEACTIVATE_PRODUCT = 'DEACTIVATE_PRODUCT',
    ACTIVATE_PRODUCT = 'ACTIVATE_PRODUCT',

    CREATE_DRAFT_IMPORT_INVOICE = 'CREATE_DRAFT_IMPORT_INVOICE',
    EDIT_DRAFT_IMPORT_INVOICE = 'EDIT_DRAFT_IMPORT_INVOICE',
    DELETE_DRAFT_IMPORT_INVOICES = 'DELETE_DRAFT_IMPORT_INVOICES',
    CONFIRM_IMPORT_INVOICE = 'CONFIRM_IMPORT_INVOICE',

    CREATE_DRAFT_RETURN_IMPORT_INVOICE = 'CREATE_DRAFT_RETURN_IMPORT_INVOICE',
    EDIT_DRAFT_RETURN_IMPORT_INVOICE = 'EDIT_DRAFT_RETURN_IMPORT_INVOICE',
    DELETE_DRAFT_RETURN_IMPORT_INVOICES = 'DELETE_DRAFT_RETURN_IMPORT_INVOICES',
    CONFIRM_RETURN_IMPORT_INVOICE = 'CONFIRM_RETURN_IMPORT_INVOICE',

    CREATE_SELLING_INVOICE = 'CREATE_SELLING_INVOICE',

    CREATE_DRAFT_RETURN_SELLING_INVOICE = 'CREATE_DRAFT_RETURN_SELLING_INVOICE',
    EDIT_DRAFT_RETURN_SELLING_INVOICE = 'EDIT_DRAFT_RETURN_SELLING_INVOICE',
    DELETE_DRAFT_RETURN_SELLING_INVOICES = 'DELETE_DRAFT_RETURN_SELLING_INVOICES',
    CONFIRM_RETURN_SELLING_INVOICE = 'CONFIRM_RETURN_SELLING_INVOICE',

    CREATE_DRAFT_STOCK_ADJUSTMENT_INVOICE = 'CREATE_DRAFT_STOCK_ADJUSTMENT_INVOICE',
    EDIT_DRAFT_STOCK_ADJUSTMENT_INVOICE = 'EDIT_DRAFT_STOCK_ADJUSTMENT_INVOICE',
    DELETE_DRAFT_STOCK_ADJUSTMENT_INVOICES = 'DELETE_DRAFT_STOCK_ADJUSTMENT_INVOICES',
    CONFIRM_STOCK_ADJUSTMENT_INVOICE = 'CONFIRM_STOCK_ADJUSTMENT_INVOICE',
}

export enum ReferenceType {
    PRODUCT = 'PRODUCT',
    PRODUCT_UNIT = 'PRODUCT_UNIT',
    USER = 'USER',
    IMPORT_INVOICE = 'IMPORT_INVOICE',
    RETURN_IMPORT_INVOICE = 'RETURN_IMPORT_INVOICE',
    SELLING_INVOICE = 'SELLING_INVOICE',
    RETURN_SELLING_INVOICE = 'RETURN_SELLING_INVOICE',
    STOCK_ADJUSTMENT_INVOICE = 'STOCK_ADJUSTMENT_INVOICE',
    OTHER = 'OTHER',
}