export enum LogCode {
    CREATE_NEW_USER = 'CREATE_NEW_USER',
    EDIT_USER_INFORMATION = 'EDIT_USER_INFORMATION',
    DEACTIVATE_USER = 'DEACTIVATE_USER',
    ACTIVATE_USER = 'ACTIVATE_USER',
    ADMIN_RESET_PASSWORD = 'ADMIN_RESET_PASSWORD',
}

export enum ReferenceType {
    PRODUCT = 'PRODUCT',
    PRODUCT_UNIT = 'PRODUCT_UNIT',
    USER = 'USER',
    IMPORT_INVOICE = 'IMPORT_INVOICE',
    RETURN_IMPORT_INVOICE = 'RETURN_IMPORT_INVOICE',
    SELLING_INVOICE = 'SELLING_INVOICE',
    RETURN_SELLING_INVOICE = 'RETURN_SELLING_INVOICE',
    STOCK_ADJUSTMENT_INVOICE = 'STOCK_ADJUSTMENT_INVOICE',
    OTHER = 'OTHER',
}