export enum ErrorCode {

    // --- USERS Module ---
    USER_ALREADY_EXISTS = 1001,
    USER_NOT_FOUND = 1002,
    FIRST_ADMIN_ACCOUNT_ALREADY_EXISTS = 1003,
    USER_CANNOT_DEACTIVATE_SELF = 1004,
    USER_ALREADY_DEACTIVATED = 1005,
    USER_ALREADY_ACTIVATED = 1006,
    OLD_PASSWORD_INCORRECT = 1007,

    CREATE_USER_SERVICE = 1101,
    GET_USER_BY_ID_SERVICE = 1102,
    GET_USER_BY_USERNAME_SERVICE = 1103,
    GET_LIST_OF_USERS_SERVICE = 1104,
    DEACTIVATE_OR_ACTIVATE_USER_SERVICE = 1105,
    EDIT_USER_SERVICE = 1106,
    FORGOT_PASSWORD_SERVICE = 1107,
    UPDATE_USER_PASSWORD_SERVICE = 1108,
    SEARCH_USERS_SERVICE = 1109,

    // --- AUTH Module ---
    USERNAME_OR_PASSWORD_INCORRECT = 2001,
    INVALID_JWT_PAYLOAD = 2002,
    INVALID_JWT_TOKEN = 2003,
    NO_ROLES_FOUND_FOR_USER = 2004,
    REQUIRED_ROLES_NOT_FOUND = 2005,
    INVALID_REFRESH_TOKEN = 2006,
    RATE_LIMIT_EXCEEDED = 2007,
    TOO_MANY_REFRESH_TOKENS = 2008,

    LOGIN_SERVICE = 2101,
    NEW_ACCESS_TOKEN_SERVICE = 2102,
    LOGOUT_SERVICE = 2103,
    VALIDATE_REFRESH_TOKEN_SERVICE = 2104,
    VALIDATE_REFRESH_TOKEN_BY_ID_SERVICE = 2105,
    REVOKE_ALL_REFRESH_TOKENS_SERVICE = 2106,

    // --- PRODUCT UNITS Module ---
    PRODUCT_UNIT_NOT_FOUND = 3001,
    PRODUCT_UNIT_NAME_ALREADY_EXISTS = 3002,
    PRODUCT_UNIT_ALREADY_ACTIVATED = 3003,
    PRODUCT_UNIT_ALREADY_DEACTIVATED = 3004,
    PRODUCT_UNIT_NOT_ACTIVE = 3005,

    CREATE_PRODUCT_UNIT_SERVICE = 3101,
    EDIT_PRODUCT_UNIT_SERVICE = 3102,
    GET_PRODUCT_UNIT_BY_ID_SERVICE = 3103,
    GET_LIST_OF_PRODUCT_UNITS_SERVICE = 3104,
    DEACTIVATE_OR_ACTIVATE_PRODUCT_UNIT_SERVICE = 3105,
    GET_PRODUCT_UNIT_HISTORY_LIST_SERVICE = 3106,
    GET_PRODUCT_UNIT_HISTORY_BY_VERSION_SERVICE = 3107,

    // --- PRODUCTS Module ---
    PRODUCT_SKU_ALREADY_EXISTS = 4001,
    PRODUCT_NOT_FOUND = 4002,
    PRODUCT_NOT_ACTIVE = 4003,
    PRODUCT_ALREADY_ACTIVATED = 4004,
    PRODUCT_ALREADY_DEACTIVATED = 4005,
    PRODUCT_STOCK_CANNOT_BE_NEGATIVE = 4006,
    PRODUCT_STOCK_HISTORY_NOT_FOUND = 4007,
    TOO_MANY_PRODUCT_NAMES = 4008,
    TOO_MANY_PRODUCT_IDS = 4009,

    CREATE_PRODUCT_SERVICE = 4101,
    EDIT_PRODUCT_SERVICE = 4102,
    GET_PRODUCT_SERVICE = 4103,
    GET_PRODUCTS_SERVICE = 4104,
    GET_PRODUCT_CASHIER_SERVICE = 4105,
    DEACTIVATE_OR_ACTIVATE_PRODUCT_SERVICE = 4106,
    GET_PRODUCT_HISTORY_LIST_SERVICE = 4107,
    GET_PRODUCT_HISTORY_BY_VERSION_SERVICE = 4108,
    UPDATE_INVENTORY_STOCK_BULK_SERVICE = 4109,
    GET_PRODUCT_STOCK_HISTORY_LIST_SERVICE = 4110,
    GET_PRODUCT_OVERVIEW_SERVICE = 4111,

    // --- INVOICES Module ---
    // --- IMPORT INVOICES (5000 - 5199) ---
    IMPORT_INVOICE_NOT_FOUND = 5001,
    TOO_MANY_IMPORT_INVOICE_PRODUCTS = 5002,
    INVOICE_NOT_DRAFT = 5003,
    INVOICE_NO_PERMISSION_DRAFT = 5004,

    CREATE_DRAFT_IMPORT_INVOICE_SERVICE = 5101,
    EDIT_DRAFT_IMPORT_INVOICE_SERVICE = 5102,
    DELETE_DRAFT_IMPORT_INVOICE_SERVICE = 5103,
    CONFIRM_IMPORT_INVOICE_SERVICE = 5104,
    GET_IMPORT_INVOICE_BY_ID_SERVICE = 5105,
    GET_LIST_OF_IMPORT_INVOICES_SERVICE = 5106,

    // --- RETURN IMPORT INVOICES (5200 - 5399) ---
    RETURN_IMPORT_INVOICE_NOT_FOUND = 5201,
    TOO_MANY_RETURN_IMPORT_INVOICE_PRODUCTS = 5202,
    IMPORT_INVOICE_NOT_RETURNABLE = 5203,

    CREATE_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 5301,
    EDIT_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 5302,
    DELETE_DRAFT_RETURN_IMPORT_INVOICE_SERVICE = 5303,
    CONFIRM_RETURN_IMPORT_INVOICE_SERVICE = 5304,
    GET_RETURN_IMPORT_INVOICE_BY_ID_SERVICE = 5305,
    GET_LIST_OF_RETURN_IMPORT_INVOICES_SERVICE = 5306,

    // --- SELLING INVOICES (5400 - 5599) ---
    SELLING_INVOICE_NOT_FOUND = 5401,
    TOO_MANY_SELLING_INVOICE_PRODUCTS = 5402,
    SELLING_INVOICE_INSUFFICIENT_STOCK = 5403,

    CREATE_SELLING_INVOICE_SERVICE = 5501,
    GET_SELLING_INVOICE_BY_ID_SERVICE = 5502,
    GET_LIST_OF_SELLING_INVOICES_SERVICE = 5503,

    // --- RETURN SELLING INVOICES (5600 - 5799) ---
    RETURN_SELLING_INVOICE_NOT_FOUND = 5601,
    TOO_MANY_RETURN_SELLING_INVOICE_PRODUCTS = 5602,
    SELLING_INVOICE_NOT_RETURNABLE = 5603,

    CREATE_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 5701,
    EDIT_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 5702,
    DELETE_DRAFT_RETURN_SELLING_INVOICE_SERVICE = 5703,
    CONFIRM_RETURN_SELLING_INVOICE_SERVICE = 5704,
    GET_RETURN_SELLING_INVOICE_BY_ID_SERVICE = 5705,
    GET_LIST_OF_RETURN_SELLING_INVOICES_SERVICE = 5706,

    // --- DTO Validation Error ---
    DTO_VALIDATION_ERROR = 8001,

    IS_NOT_EMPTY_ERROR = 8100,
    IS_STRING_ERROR = 8101,
    IS_NUMBER_ERROR = 8102,
    IS_BOOLEAN_ERROR = 8103,
    IS_ARRAY_ERROR = 8104,
    IS_OBJECT_ERROR = 8105,
    IS_DATE_ERROR = 8106,
    IS_EMAIL_ERROR = 8107,
    IS_URL_ERROR = 8108,
    IS_IP_ERROR = 8109,
    IS_INT_ERROR = 8110,
    IS_ENUM_ERROR = 8111,
    MIN_LENGTH_ERROR = 8112, // When a property is less than the minimum length.
    MAX_LENGTH_ERROR = 8113, // When a property is greater than the maximum length.
    MIN_ERROR = 8114, // When a property is less than the minimum value.
    MAX_ERROR = 8115, // When a property is greater than the maximum value.
    MATCHES_ERROR = 8116, // When a property does not match the regex pattern.
    IS_STRONG_PASSWORD_ERROR = 8117, // When a property is not a strong password.
    WHITELISTED_ERROR = 8118, // When a property is not allowed by the DTO.
    IS_UUID_ERROR = 8119, // @IsUUID / @IsUUID(..., { each: true })
    IS_DATE_STRING_ERROR = 8120, // @IsDateString
    IS_IN_ERROR = 8121, // @IsIn
    NESTED_VALIDATION_ERROR = 8122, // nestedValidation — @ValidateNested when value is not a valid object/array
    ARRAY_MAX_SIZE_ERROR = 8123, // @ArrayMaxSize
    ARRAY_UNIQUE_ERROR = 8124, // @ArrayUnique
    INVOICE_DATE_RANGE_INVALID = 8125, // @Validate(InvoiceDateRangeConstraint) — range / max span
    UNKNOWN_CONSTRAINT_ERROR = 8199, // When a constraint is not found in the constraint error code map.


    // --- COMMON Module ---
    DB_CONNECTION_ERROR = 9001,
    RACE_CONDITION_ERROR = 9002,
    DB_QUERY_ERROR = 9003,
    HTTP_EXCEPTION = 9901,
    UNKNOWN_ERROR = 9999,
}
